CREATE TABLE MEMBERS (
   MEM_NUM   varchar2(30)    ,
   MEM_PW   varchar2(30)  ,
   MEM_NAME   varchar2(30)   ,
   MEM_PHONE   varchar2(30)   ,
   MEM_AREA   number(20)      
);

CREATE TABLE GIGI_SENSORS (
   GIGI_NUM   NUMBER(20)     ,
   GIGI_NAME   varchar2(30)     ,
   GIGI_VOL   varchar2(30)      ,
   GIGI_TEMP   varchar2(30)      ,
   GIGI_HUM   varchar2(30)      ,
   GIGI_AREA   number(20)	,
   GIGI_CHECK   DATE     
);

CREATE TABLE COMPLAINTS (
   COM_NUM   NUMBER(20)      ,
   GIGI_NAME   varchar2(30)    ,
   COM_TITLE   varchar2(30)   ,
   COM_CONTENT   varchar2(200)   ,
   COM_DATE   DATE 
);

CREATE TABLE GIGI_NAMES (
   GIGI_NAME   varchar2(30)  ,
   GIGI_LOCATION   varchar2(30),
   GIGI_COUNT   number(20),
   GIGI_FIRST_CHECK   DATE,
   GIGI_AREA   number(30)   
);

ALTER TABLE MEMBERS ADD CONSTRAINT PK_MEMBERS PRIMARY KEY (
   MEM_NUM
);

ALTER TABLE GIGI_SENSORS ADD CONSTRAINT PK_GIGI_SENSORS PRIMARY KEY (
   GIGI_NUM
);

ALTER TABLE COMPLAINTS ADD CONSTRAINT PK_COMPLAINTS PRIMARY KEY (
   COM_NUM
);

ALTER TABLE GIGI_NAMES ADD CONSTRAINT PK_GIGI_NAMES PRIMARY KEY (
   GIGI_NAME
);

ALTER TABLE GIGI_SENSORS ADD CONSTRAINT GIGI_SENSORS_1 FOREIGN KEY (
   GIGI_NAME
)
REFERENCES GIGI_NAMES (
   GIGI_NAME
);

ALTER TABLE COMPLAINTS ADD CONSTRAINT COMPLAINTS_1 FOREIGN KEY (
   GIGI_NAME
)
REFERENCES GIGI_NAMES (
   GIGI_NAME
);


drop table MEMBERS
drop table GIGI_SENSORS
drop table COMPLAINTS
drop table GIGI_NAMES
