CREATE TABLE  MEMBERS  (
    MEM_NUM    varchar2      NOT NULL,
    MEM_AREA    INT      NOT NULL,
    MEM_PW    varchar2      NULL,
    MEM_NAME    varchar2      NULL,
    MEM_PHONE    varchar2      NULL
);

CREATE TABLE GIGI_SENSORS  (
    GIGI_NUM    NUMBER      NOT NULL,
    GIGI_NAME    varchar2      NOT NULL,
    MEM_AREA    INT      NOT NULL,
    GIGI_VOL    varchar2      NULL,
    GIGI_TEMP    varchar2      NULL,
    GIGI_HUM    varchar2      NULL,
    GIGI_AREA    INT      NULL,
    GIGI_CHECK    DATE      NOT NULL
);

CREATE TABLE  COMPLAINTS  (
    COM_NUM    NUMBER      NOT NULL,
    GIGI_NAME    varchar2      NOT NULL,
    COM_TITLE    varchar2      NULL,
    COM_CONTENT    varchar2      NULL,
    COM_DATE    DATE      NULL
);

CREATE TABLE  GIGI_NAMES  (
    GIGI_NAME    varchar2      NOT NULL,
    MEM_AREA    INT      NOT NULL,
    GIGI_LOCATION    varchar2      NULL,
    GIGI_AREA    INT      NULL,
    GIGI_COUNT    INT      NULL,
    GIGI_FIRST_CHECK    DATE      NULL
);

ALTER TABLE  MEMBERS  ADD CONSTRAINT  PK_MEMBERS  PRIMARY KEY (
    MEM_NUM ,
    MEM_AREA 
);

ALTER TABLE  GIGI_SENSORS  ADD CONSTRAINT  PK_GIGI_SENSORS  PRIMARY KEY (
    GIGI_NUM ,
    GIGI_NAME ,
    MEM_AREA 
);

ALTER TABLE  COMPLAINTS  ADD CONSTRAINT  PK_COMPLAINTS  PRIMARY KEY (
    COM_NUM ,
    GIGI_NAME 
);

ALTER TABLE  GIGI_NAMES  ADD CONSTRAINT  PK_GIGI_NAMES  PRIMARY KEY (
    GIGI_NAME ,
    MEM_AREA 
);

ALTER TABLE  GIGI_SENSORS  ADD CONSTRAINT  FK_GIGI_NAMES_TO_GIGI_SENSORS_1  FOREIGN KEY (
    GIGI_NAME 
)
REFERENCES  GIGI_NAMES  (
    GIGI_NAME 
);

ALTER TABLE  GIGI_SENSORS  ADD CONSTRAINT  FK_GIGI_NAMES_TO_GIGI_SENSORS_2  FOREIGN KEY (
    MEM_AREA 
)
REFERENCES  GIGI_NAMES  (
    MEM_AREA 
);

ALTER TABLE  COMPLAINTS  ADD CONSTRAINT  FK_GIGI_NAMES_TO_COMPLAINTS_1  FOREIGN KEY (
    GIGI_NAME 
)
REFERENCES  GIGI_NAMES  (
    GIGI_NAME 
);

ALTER TABLE  GIGI_NAMES  ADD CONSTRAINT  FK_MEMBERS_TO_GIGI_NAMES_1  FOREIGN KEY (
    MEM_AREA 
)
REFERENCES  MEMBERS  (
    MEM_AREA 
);